David je t'aime ( raph aussi )

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import polars as pl

print("All packages imported successfully!")

All packages imported successfully!

In [2]:
import glob

path_list_spy = glob.glob('data_arthur/SPY.P/*.parquet')
path_list_aapl = glob.glob('data_arthur/AAPL.OQ/*.parquet')
path_list_spy[0]

'data_arthur/SPY.P/2009-03-10-SPY.P-trade.parquet'

In [3]:
lf = pl.scan_parquet(path_list_spy[0])

lf.schema

/var/folders/mc/qf75k40s6ns_nr8c35wdmp400000gn/T/ipykernel_12402/529268217.py:3: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  lf.schema

Schema([('xltime', Float64),
        ('trade-price', Float64),
        ('trade-volume', Int32),
        ('trade-stringflag', String),
        ('trade-rawflag', String)])

In [4]:

lf.head(20).collect()[['xltime', 'trade-price', 'trade-volume']]

shape: (20, 3)
┌──────────────┬─────────────┬──────────────┐
│ xltime       ┆ trade-price ┆ trade-volume │
│ ---          ┆ ---         ┆ ---          │
│ f64          ┆ f64         ┆ i32          │
╞══════════════╪═════════════╪══════════════╡
│ 39882.343799 ┆ 68.95       ┆ 100          │
│ 39882.343871 ┆ 69.0        ┆ 200          │
│ 39882.343999 ┆ 69.0        ┆ 100          │
│ 39882.346562 ┆ 69.2        ┆ 100          │
│ 39882.352965 ┆ 69.24       ┆ 200          │
│ …            ┆ …           ┆ …            │
│ 39882.387891 ┆ 69.21       ┆ 3500         │
│ 39882.408103 ┆ 69.32       ┆ 500          │
│ 39882.411781 ┆ 69.37       ┆ 500          │
│ 39882.412662 ┆ 69.45       ┆ 1000         │
│ 39882.414981 ┆ 69.42       ┆ 300          │
└──────────────┴─────────────┴──────────────┘

In [7]:
lf.describe()

shape: (9, 6)
┌────────────┬──────────────┬─────────────┬──────────────┬──────────────────┬─────────────────┐
│ statistic  ┆ xltime       ┆ trade-price ┆ trade-volume ┆ trade-stringflag ┆ trade-rawflag   │
│ ---        ┆ ---          ┆ ---         ┆ ---          ┆ ---              ┆ ---             │
│ str        ┆ f64          ┆ f64         ┆ f64          ┆ str              ┆ str             │
╞════════════╪══════════════╪═════════════╪══════════════╪══════════════════╪═════════════════╡
│ count      ┆ 266851.0     ┆ 266851.0    ┆ 266851.0     ┆ 266851           ┆ 266851          │
│ null_count ┆ 0.0          ┆ 0.0         ┆ 0.0          ┆ 0                ┆ 0               │
│ mean       ┆ 39882.693275 ┆ 71.342313   ┆ 408.154191   ┆ null             ┆ null            │
│ std        ┆ 0.094766     ┆ 0.712061    ┆ 3140.006072  ┆ null             ┆ null            │
│ min        ┆ 39882.343799 ┆ 68.95       ┆ 0.0          ┆ auction          ┆                 │
│ 25%        ┆ 39882.600843 ┆ 70.96       ┆ 100.0        ┆ null             ┆ null            │
│ 50%        ┆ 39882.678197 ┆ 71.58       ┆ 200.0        ┆ null             ┆ null            │
│ 75%        ┆ 39882.785754 ┆ 71.86       ┆ 300.0        ┆ null             ┆ null            │
│ max        ┆ 39882.999991 ┆ 72.66       ┆ 900000.0     ┆ uncategorized    ┆ [USER           │
│            ┆              ┆             ┆              ┆                  ┆ ]High         … │
└────────────┴──────────────┴─────────────┴──────────────┴──────────────────┴─────────────────┘

In [10]:
lf_aapl = pl.scan_parquet(path_list_aapl[0])
lf_aapl.schema
lf_aapl.head(20).collect()[['V1', 'trade-price', 'trade-volume']]

/var/folders/mc/qf75k40s6ns_nr8c35wdmp400000gn/T/ipykernel_12402/3478606530.py:2: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  lf_aapl.schema

shape: (20, 3)
┌──────────────┬─────────────┬──────────────┐
│ V1           ┆ trade-price ┆ trade-volume │
│ ---          ┆ ---         ┆ ---          │
│ f64          ┆ f64         ┆ f64          │
╞══════════════╪═════════════╪══════════════╡
│ 40070.5022   ┆ 170.82      ┆ 329.0        │
│ 40070.502627 ┆ 170.82      ┆ 100.0        │
│ 40070.50826  ┆ 171.0       ┆ 100.0        │
│ 40070.514157 ┆ 171.02      ┆ 300.0        │
│ 40070.517836 ┆ 170.98      ┆ 160.0        │
│ …            ┆ …           ┆ …            │
│ 40070.530896 ┆ 171.1       ┆ 138.0        │
│ 40070.53092  ┆ 171.1       ┆ 138.0        │
│ 40070.533238 ┆ 171.02      ┆ 100.0        │
│ 40070.536235 ┆ 171.05      ┆ 500.0        │
│ 40070.536393 ┆ 171.05      ┆ 500.0        │
└──────────────┴─────────────┴──────────────┘